name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get musicbot version and image tag from version file
      - name: Set version
        run: echo "RELEASE_VERSION=$(cat version)" >> $GITHUB_ENV

      # Set up buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          build-args: |
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          push: true
          tags: nastye/jagrosh-musicbot:${{ env.RELEASE_VERSION }}
  gce-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Get musicbot version and image tag from version file
      - name: Set version
        run: echo "RELEASE_VERSION=$(cat version)" >> $GITHUB_ENV
 
      # Setup gcloud CLI
      - name: Gcloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCE_SA_CREDENTIALS_JSON }}
      - name: GCloud setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '487.0.0'
          project_id: ${{ secrets.GCE_PROJECT_ID }}
      - name: Instance update
        run: |
          gcloud compute instances update-container "${{ secrets.GCE_INSTANCE }}" \
            --zone "${{ secrets.GCE_INSTANCE_ZONE }}" \
            --container-image "nastye/jagrosh-musicbot:${{ env.RELEASE_VERSION }}"
